name: Docker - API

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Run Workflow - Leave Empty For Current Branch"
        required: false
        type: string

  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "docker/api/**"

permissions:
  id-token: write
  contents: read

jobs:
  API:
    name: Build & Push ACR
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Determine Branch & Environment
      - name: Determine Branch & Enviroment
        id: detect-env
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"

           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
            BRANCH="$INPUT_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
            BRANCH="$DISPATCH_BRANCH"

          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH="$GITHUB_BASE_REF"

          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          echo "Branch: $BRANCH"

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
            esac

          TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

        # Read Terraform TFVARS For Environment
      - name: Terraform Variables
        id: tfvars
        run: |
          TFVARS_FILE="$TFVARS_FILE"
          if [ ! -f "$TFVARS_FILE" ]; then
            echo "TFVARS File Not Found: $TFVARS_FILE"
            exit 1
          fi

          RG_NAME=$(grep -E '^resource_group_name' "$TFVARS_FILE" | awk -F'=' '{print $2}' | xargs)
          ACR_NAME=$(grep -E '^acr_name' "$TFVARS_FILE" | awk -F'=' '{print $2}' | xargs)

          RG_NAME="${RG_NAME//$'\r'/}"
          ACR_NAME="${ACR_NAME//$'\r'/}"

          echo "RG_NAME=$RG_NAME" >> $GITHUB_ENV
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV

          echo "RG_NAME=$RG_NAME"
          echo "ACR_NAME=$ACR_NAME"

        # Azure Authentication
      - name: Azure Authentication
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Query Azure For ACR login Server
      - name: Query Azure ACR Login Server
        id: query-acr
        run: |
          echo "Searching For ACR Login Server"

          ACR_LOGIN_SERVER=$(az acr show \
            -n $ACR_NAME \
            -g $RG_NAME \
            --query "loginServer" \
            -o tsv)

          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
          echo "Confirmed ACR Login Server"

        # ACR Login
      - name: Login To ACR via RBAC
        run: |
          echo "Logging Into ACR.."
          az acr login --name $ACR_NAME

        # List Docker Folders
      - name: List Docker Files
        run: ls -l docker/api

        # Docker Buildx Setup
      - name: Docker Buildx Setup dock
        uses: docker/setup-buildx-action@v2

        # Build & Push API Docker Image
      - name: Build & Push API Docker Image
        shell: bash
        run: |
          IMAGE_FULL=$(grep -E '^api_worker_image' "$TFVARS_FILE" | awk -F'=' '{print $2}' | xargs)
          IMAGE_FULL="${IMAGE_FULL//$'\r'/}"

          if [ -z "$IMAGE_FULL" ]; then
            echo "api_worker_image Missing In $TFVARS_FILE"
            exit 1
          fi

          echo "TFVARS Image: $IMAGE_FULL"

          IMAGE_PATH=$(echo "$IMAGE_FULL" | cut -d'/' -f2)
          IMAGE_NAME=$(echo "$IMAGE_PATH" | cut -d':' -f1)
          IMAGE_TAG=$(echo "$IMAGE_PATH" | cut -d':' -f2)

          if [ -z "$IMAGE_NAME" ] || [ -z "$IMAGE_TAG" ]; then
            echo "Failed To Parse Image Name Or Tag"
            exit 1
          fi

          FULL_IMAGE="$ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG"

          echo "Building API Docker Image"
          docker build -t "$FULL_IMAGE" ./docker/api/api-docker

          echo "Docker Push - $ENV"
          docker push "$FULL_IMAGE"

          echo "Image Pushed To ACR"
