name: Pipeline Infrastructure Deployment

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Deploy ( dev | staging | main )"
        required: true
        type: string

permissions:
  contents: read

jobs:
  # Terraform Infrastructure Deployment
  Infrastructure-Deployment:
    name: Deployment
    uses: ./.github/workflows/deployment-multi-phase-terraform.yml
    with:
      branch: ${{ inputs.branch }}
