name: Pipeline - Pre Deployment

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Run Workflow - Leave Empty For Current Branch"
        required: false
        type: string

  pull_request:
    branches:
      - main
    paths:
      - modules/**
      - environments/**
      - main.tf
      - variables.tf

jobs:
  Terraform-Static-Analysis:
    runs-on: ubuntu-latest

    env:
      TF_LOG: ERROR
      INPUT_BRANCH: ${{ inputs.branch }}
      DISPATCH_BRANCH: ${{ github.event.inputs.branch }}

    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}
      tfvars_file: ${{ steps.detect-env.outputs.tfvars }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version

      - name: Determine Branch & Environment
        id: detect-env
        shell: bash
        run: |
          echo "Determining Branch & Environment..."
           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
             BRANCH="$INPUT_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
             BRANCH="$DISPATCH_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
             BRANCH="$GITHUB_BASE_REF"

           else
             BRANCH="${GITHUB_REF#refs/heads/}"
           fi

           echo "Branch: $BRANCH"

           case "$BRANCH" in
             dev) ENV="dev" ;;
             staging) ENV="staging" ;;
             main) ENV="production" ;;
             *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
           esac

           TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"

           echo "env=$ENV" >> $GITHUB_OUTPUT
           echo "tfvars=$TFVARS_FILE" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

  Terraform-Linting:
    runs-on: ubuntu-latest
    needs: Terraform-Static-Analysis

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: .
        run: |
          echo "Initializing Terraform..."
          terraform init -backend=false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: TFLint Config
        run: |
          cat <<EOF > .tflint.hcl
          config {
            format = "compact"
          }

          plugin "azurerm" {
            enabled = true
            source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
            version = "0.27.0"
          }

          rule "terraform_unused_declarations" {
            enabled = true
            level   = "WARNING"
          }

          rule "terraform_required_providers" {
            enabled = true
          }
          EOF

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --format compact

  Security:
    runs-on: ubuntu-latest
    needs: Terraform-Linting

    env:
      TFVARS_FILE: ${{ needs.Terraform-Static-Analysis.outputs.tfvars_file }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          var_file: ${{ env.TFVARS_FILE }}
          check: CKV_AZURE_*
          soft_fail: false
          output_format: cli
          download_external_modules: true

          # HTTP (160) - KV Pure Protection (110) - CA Local Auth (236) - AKS SLA Paid SKU (170) - Min 50 Pods - AKS API Auth IP -CA Diabled Public Network (124) - SA Blob Public Access (190) - SA Public Access (59) - Queue Logging (33) - ACR Disabled Public Network (139) - ACR Dataend Point (237) - AKS Private CLuster (115) - Critical System Pods (232) - KV Recoverable (42) - App GW HTTPs (217) - App GW SSL (218) - SB DOuble Encrypt (199) - SB Public Network (204) - App GW WAF (120) - Search Identity, SA Replication (206), Cognitive Search SLA search index queries (209) & (208)
          skip_check: CKV_AZURE_160,CKV_AZURE_110,CKV_AZURE_236,CKV_AZURE_170,CKV_AZURE_168,CKV_AZURE_6,CKV_AZURE_124,CKV_AZURE_190,CKV_AZURE_59,CKV_AZURE_33,CKV_AZURE_193,CKV_AZURE_237,CKV_AZURE_115,CKV_AZURE_232,CKV_AZURE_42,CKV_AZURE_217,CKV_AZURE_218,CKV_AZURE_199,CKV_AZURE_204,CKV_AZURE_120,CKV_AZURE_139,CKV_AZURE_207,CKV_AZURE_233,CKV_AZURE_206,CKV_AZURE_209,CKV_AZURE_208

      - name: Install Trivy
        run: |
          echo "Installing Trivy Scanner"
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo "Trivy Installed Successfully"
          ./bin/trivy --version

        # Trivy Scan - Secrets Scan
      - name: Trivy Secrets Scan
        run: |
          echo "Running Trivy Secrets Scan..."
          ./bin/trivy fs ./ \
            --scanners secret \
            --format table \
            --severity CRITICAL,HIGH \
            --exit-code 1
          echo "Secrets Scan Completed"

      # Clear Cache
      - name: Clear Trivy Cache
        run: |
          echo "Clearing Trivy Cache"
           rm -rf ~/.cache/trivy
           echo "Cleanup Complete"

        # Trivy Scan - Root Modules
      - name: Trivy IAC Scan
        run: |
          echo "Running Trivy Module IAC Scan..."
          ./bin/trivy config . \
            --tf-vars ${{ env.TFVARS_FILE }} \
            --skip-dirs environments/terraform-backend \
            --format table \
            --severity CRITICAL,HIGH || true
            echo "Terraform Config Scan Completed"
